
class Common(object):

    POLAR_TYPE = "POLAR"
    BROWN_TYPE = "BROWN"
    BLACK_TYPE = "BLACK"
    GUMMY_TYPE = "GUMMY"
    WRONG_TYPE = "WRONG_TYPE"

    BEAR_TYPES = [POLAR_TYPE, BROWN_TYPE, BLACK_TYPE, GUMMY_TYPE]
